### ISSUE TITLE
SQL error when saving Filler Lists or Custom Shows

### ISSUE THREAD

**Issue by pavlov70** [chrisbenincasa/tunarr#931]
When saving a Filler List or Custom Show, a foreign key constraint error is thrown. As a result I'm unable to add the list to a channel or even delete the list. I have tried creating lists w/ single and multiple entries, deleting the db between each attempt. I am running the below in a docker.

BTW this app is really cool. Loading a channel is under 5 seconds once I got HW acceleration working properly.

Version: 0.15.4
FFMPEG: N-115388-ge9197db4f7
NodeJS: 20.18.0

`2024-11-04T00:09:37.865Z [error]: Query error: 'insert into "channel_filler_show" ("cooldown", "channel_uuid", "filler_show_uuid", "weight") values (?, ?, ?, ?)'
[30,"4c9a2189-7bd6-4a50-9665-74e3f881c0d5","778deddd-a6a0-43fa-802c-bc5a2712cd54",100] 
    err: {
      "type": "SqliteError",
      "message": "FOREIGN KEY constraint failed",
      "stack":
          SqliteError: FOREIGN KEY constraint failed
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:167260:49)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:165287:35)
              at file:///tunarr/server/build/bundle.js:158281:39
              at #run (file:///tunarr/server/build/bundle.js:165345:18)
              at SingleConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:165337:37)
              at _DefaultQueryExecutor.provideConnection (file:///tunarr/server/build/bundle.js:165169:37)
              at _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:158280:23)
              at _InsertQueryBuilder.execute (file:///tunarr/server/build/bundle.js:155857:47)
              at _InsertQueryBuilder.executeTakeFirst (file:///tunarr/server/build/bundle.js:155876:33)
              at _InsertQueryBuilder.executeTakeFirstOrThrow (file:///tunarr/server/build/bundle.js:155888:31)
              at file:///tunarr/server/build/bundle.js:184140:77
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async file:///tunarr/server/build/bundle.js:165783:24
              at async DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:165139:14)
              at async ChannelDB.updateChannel (file:///tunarr/server/build/bundle.js:184127:5)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:189780:34)
      "code": "SQLITE_CONSTRAINT_FOREIGNKEY"
    }
2024-11-04T00:09:37.867Z [error]: /api/channels/:id 
    err: {
      "type": "SqliteError",
      "message": "FOREIGN KEY constraint failed",
      "stack":
          SqliteError: FOREIGN KEY constraint failed
              at SqliteConnection.executeQuery (file:///tunarr/server/build/bundle.js:167260:49)
              at connection.executeQuery (file:///tunarr/server/build/bundle.js:165287:35)
              at file:///tunarr/server/build/bundle.js:158281:39
              at #run (file:///tunarr/server/build/bundle.js:165345:18)
              at SingleConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:165337:37)
              at _DefaultQueryExecutor.provideConnection (file:///tunarr/server/build/bundle.js:165169:37)
              at _DefaultQueryExecutor.executeQuery (file:///tunarr/server/build/bundle.js:158280:23)
              at _InsertQueryBuilder.execute (file:///tunarr/server/build/bundle.js:155857:47)
              at _InsertQueryBuilder.executeTakeFirst (file:///tunarr/server/build/bundle.js:155876:33)
              at _InsertQueryBuilder.executeTakeFirstOrThrow (file:///tunarr/server/build/bundle.js:155888:31)
              at file:///tunarr/server/build/bundle.js:184140:77
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async file:///tunarr/server/build/bundle.js:165783:24
              at async DefaultConnectionProvider.provideConnection (file:///tunarr/server/build/bundle.js:165139:14)
              at async ChannelDB.updateChannel (file:///tunarr/server/build/bundle.js:184127:5)
              at async Object.<anonymous> (file:///tunarr/server/build/bundle.js:189780:34)
      "code": "SQLITE_CONSTRAINT_FOREIGNKEY"
    }
`

**Comment by chrisbenincasa** [comment]
Thanks! I'll take a look. This is definitely due to a recent change I made.

**Comment by chrisbenincasa** [comment]
Hmmm, unfortunately I didn't think this is as obvious as I had hoped it'd be. I can't get a reproduction on my end. Still looking.

**Comment by SuperBee516** [comment]
Im also having an issue when trying to save my fillers on a channel. It simply wont save.

```
2024-11-04T20:45:44.021Z [error]: Query error: 'insert into "channel_filler_show" ("cooldown", "channel_uuid", "filler_show_uuid", "weight") values (?, ?, ?, ?)'
[30,"c96b57f4-12cd-4f28-8db8-5b465a3130d8","583b122a-cb3c-40ff-8a43-a5b46474bd7d",100] 
    err: {
      "type": "SqliteError",
      "message": "FOREIGN KEY constraint failed",
      "stack":
          SqliteError: FOREIGN KEY constraint failed
              at SqliteConnection.executeQuery (file:///c:/tunarr/bundle.js:167260:49)
              at connection.executeQuery (file:///c:/tunarr/bundle.js:165287:35)
              at file:///c:/tunarr/bundle.js:158281:39
              at #run (file:///c:/tunarr/bundle.js:165345:18)
              at SingleConnectionProvider.provideConnection (file:///c:/tunarr/bundle.js:165337:37)
              at _DefaultQueryExecutor.provideConnection (file:///c:/tunarr/bundle.js:165169:37)
              at _DefaultQueryExecutor.executeQuery (file:///c:/tunarr/bundle.js:158280:23)
              at _InsertQueryBuilder.execute (file:///c:/tunarr/bundle.js:155857:47)
              at _InsertQueryBuilder.executeTakeFirst (file:///c:/tunarr/bundle.js:155876:33)
              at _InsertQueryBuilder.executeTakeFirstOrThrow (file:///c:/tunarr/bundle.js:155888:31)
              at file:///c:/tunarr/bundle.js:184140:77
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async file:///c:/tunarr/bundle.js:165783:24
              at async DefaultConnectionProvider.provideConnection (file:///c:/tunarr/bundle.js:165139:14)
              at async ChannelDB.updateChannel (file:///c:/tunarr/bundle.js:184127:5)
              at async Object.<anonymous> (file:///c:/tunarr/bundle.js:189780:34)
      "code": "SQLITE_CONSTRAINT_FOREIGNKEY"
    }

```

**Comment by chrisbenincasa** [comment]
Would either of you be willing to send me your tunarr database file so I can compare it to my working version on my machine?

**Comment by pavlov70** [comment]
Thanks for investigating. I would be happy to. How shall I get it to you and is there anything private in it (api key, etc)?

**Comment by pavlov70** [comment]
A bit more info in case it helps. My install was fresh 0.15.4 and I'm betting SuperBee516 is a relatively new install. I installed 0.15.4 on my windows machine and received the same error. I blew that away and installed 0.14.2 and filler works properly. I then upgraded back to 0.15.4 and filler continues to work properly, even adding new ones.

I should also add previously I was having a lot of issues with time slots disappearing and general issues saving. For example, I couldn't have a timeslot later than 7pm. On initial testing, all issues (except the 0 byte uploaded image) are no more after starting at 0.14, creating an initial channel, and then upgrading back. I imagine my other issues were also due to missing keys or columns that I just wasn't seeing as I wasn't paying close attention to the console. 

Going to try doing the same on my linux docker and see if I get the same results.

**Comment by chrisbenincasa** [comment]
Appreciate the details. There were some huge changes to how db migrations work in 0.15. I tried my best to make it  smooth migration for existing installs which used an old method for these migrations and also for new installs. It seems like maybe the migrations for fresh installs is broken, but I'll have to take a look. 

Regarding time slots..this could be related but I'm not sure. I don't think there any missing columns, since that would break a ton of stuff. There also hasn't been major changes in logic there recently (0.15.x). I'll look into that once we get the db migrations sorted. @SuperBee516 sent me their database so I should be able to use that to figure out what's up.

**Comment by chrisbenincasa** [comment]
Also @pavlov70 can you clarify - you mean you were having errors saving things on the 0.15.x line?

**Comment by pavlov70** [comment]
Thanks again for all of your hard work. 

To clarify my above statement, yes it was the 15.x line (fresh install). I don't want to confuse issues so let me do a bit more testing . 

 I just downloaded 15.5 and I can create and add filler lists. I do however receive the following error when I try to delete a filler list. 

2024-11-05T09:38:46.413Z [info]: XMLTV Updated at 11/5/2024, 9:38:46 AM
2024-11-05T09:44:57.268Z [error]: /api/filler-lists/:id
    err: {
      "type": "TypeError",
      "message": "reduce_default(...).else is not a function",
      "stack":
          TypeError: reduce_default(...).else is not a function
              at file:///D:/tunarr/bundle.js:180737:15
              at parseUpdateObjectExpression (file:///D:/tunarr/bundle.js:144775:43)
              at parseUpdate (file:///D:/tunarr/bundle.js:144771:10)
              at _UpdateQueryBuilder.set (file:///D:/tunarr/bundle.js:146691:74)
              at file:///D:/tunarr/bundle.js:180710:49
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async file:///D:/tunarr/bundle.js:154379:24
              at async DefaultConnectionProvider.provideConnection (file:///D:/tunarr/bundle.js:153735:14)
              at async FillerDB.deleteFiller (file:///D:/tunarr/bundle.js:180684:5)
              at async Object.<anonymous> (file:///D:/tunarr/bundle.js:189371:7)
    }

**Comment by chrisbenincasa** [comment]
@pavlov70 did you pull the edge release or something? I haven't cut the release for 0.15.5 officially yet

**Comment by chrisbenincasa** [comment]
https://github.com/chrisbenincasa/tunarr/commit/95bf2b380adcb5ff3e0ade7e04c7a10ca0cdbbb0 should fix deleting fillers

**Comment by chrisbenincasa** [comment]
Not at all! This is very useful. I just wanted to confirm the version
